### ISSUE TITLE
ValueError: Cannot feed value of shape (11, 16, 160, 160, 3) for Tensor 'Placeholder:0', which has shape '(12, 16, 160, 160, 3)'

### ISSUE THREAD

**Issue by AndyHon** [hx173149/C3D-tensorflow#110]
It is always one less than batch_size, sometimes two. I don't know why. please help me.thanks
Traceback (most recent call last):
File "/home/p18301147/pseudo-3d-tensorflow/train.py", line 142, in
run()
File "/home/p18301147/pseudo-3d-tensorflow/train.py", line 120, in run
label_placeholder:train_labels})
File "/home/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 905, in run
run_metadata_ptr)
File "/home/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1116, in _run
str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (11, 16, 160, 160, 3) for Tensor 'Placeholder:0', which has shape '(12, 16, 160, 160, 3)'

**Comment by AmmarKamoona** [comment]
Hi there, 
I got this problem but I solved by placing the UCF101 within same root
