### ISSUE TITLE
ValueError: setting an array element with a sequence.

### ISSUE THREAD

**Issue by duynn912** [hx173149/C3D-tensorflow#115]
Does anyone have any idea for this problem? Please help me out. I am using tensorflow 1.7.0 and numpy 1.14.5.
Traceback (most recent call last):
  File "predict_c3d_ucf101.py", line 155, in <module>
    tf.app.run()
  File "/home/tinhh/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "predict_c3d_ucf101.py", line 152, in main
    run_test()
  File "predict_c3d_ucf101.py", line 133, in run_test
    start_pos=next_start_pos
  File "/home/tinhh/nnduy/tracvid/C3D-tensorflow/input_data.py", line 106, in read_clip_and_label
    np_arr_data = np.array(data).astype(np.float32)
ValueError: setting an array element with a sequence.

**Comment by sunshineZXJ** [comment]
I have same problem.Do you solve it?
