### ISSUE TITLE
what is the edition of the tensorflow

### ISSUE THREAD

**Issue by hxtsch** [hx173149/C3D-tensorflow#24]
I have got the problem when I run the code.
Could you please tell me the edition of your tensorflow?
Thanks.

**Comment by kingrain213** [comment]
I have met the question too, as below， maybe the edition is different，mine is "1.2.1",and on cpu, what and where should I change to make it run on cpu?
_____________________________________________________________________________________________________
Traceback (most recent call last):
  File "train_c3d_ucf101.py", line 273, in <module>
    tf.app.run()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_c3d_ucf101.py", line 270, in main
    run_training()
  File "train_c3d_ucf101.py", line 192, in run_training
    logits = tf.concat(0, logits)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1044, in concat
    ).assert_is_compatible_with(tensor_shape.scalar())
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 732, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (0,) and () are incompatible

**Comment by hx173149** [comment]
The latest code has supported TF 1.2 version now.
