### ISSUE TITLE
Error in training

### ISSUE THREAD

**Issue by nainadhingra2012** [hx173149/C3D-tensorflow#42]
Hello,

I am trying to reproduce the results of yours. I get an error while training.

(venv) naina@naina-K401UQK:~/Desktop/internship/tensorflowC3D/C3D-tensorflow$ python train_c3d.py
/home/naina/semi/venv/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-01-28 02:17:34.213275: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-01-28 02:17:34.300876: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-01-28 02:17:34.301330: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce 940MX major: 5 minor: 0 memoryClockRate(GHz): 1.2415
pciBusID: 0000:01:00.0
totalMemory: 1.96GiB freeMemory: 768.56MiB
2018-01-28 02:17:34.301356: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce 940MX, pci bus id: 0000:01:00.0, compute capability: 5.0)
Train the model from scratch
Traceback (most recent call last):
  File "train_c3d.py", line 342, in <module>
    tf.app.run()
  File "/home/naina/semi/venv/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_c3d.py", line 338, in main
    run_training()
  File "train_c3d.py", line 262, in run_training
    labels_placeholder: train_labels})
  File "/home/naina/semi/venv/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/naina/semi/venv/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1096, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (10, 0) for Tensor u'Placeholder:0', which has shape '(?, 16, 128, 128, 3)'

Can you please suggest what could be the problem?

**Comment by perfectFeng** [comment]
hi，
I encountered similar problems before, the reason is that the dimension of read video data is not consistent with the settings in placeholder, so you can check the dimension of your read video data.
Hope to help you

**Comment by nainadhingra2012** [comment]
Hi,

I am using the dataset ucf101, does it still bound to have dimension error as the author also used the same dataset. What changes did you make in this case?

**Comment by perfectFeng** [comment]
Your error message shows that there is a problem with the batch of the read data, so you can print out the dimension of the read data to check if it's the same as the dimension set by the placeholder.My problem is that I can't read the data which is a liitle different with yours

**Comment by liyanan12345** [comment]
hi,
i have same problem, you have solved it,  could you tell me what you have changed?
