### ISSUE TITLE
Error in using "train_c3d_ucf101.py 

### ISSUE THREAD

**Issue by joul55320** [hx173149/C3D-tensorflow#43]
I’m trying to run the file “train_c3d_ucf101.py”,
but always appear the error messange.

```
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36:
 FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-01-26 17:22:17.583579: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-01-26 17:22:17.583618: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-01-26 17:22:17.583638: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-01-26 17:22:17.583657: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-01-26 17:22:17.583662: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "train_c3d_ucf101.py", line 261, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_c3d_ucf101.py", line 258, in main
    run_training()
  File "train_c3d_ucf101.py", line 223, in run_training
    labels_placeholder: train_labels
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 975, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (20, 0) for Tensor u'Placeholder:0', which has shape '(20, 16, 112, 112, 3)'
```

I was download on https://github.com/hx173149/C3D-tensorflow at 01/19/2018,
and the test environment is 
        python = 2.7
        tensorflow = 1.4.1
I also install athena-jot and Pillow

**Comment by hfercc** [comment]
You may try to use 'train.list' but not 'list/train.list' in train_c3d_ucf101.py at line 215. 
That works for me.

**Comment by LiXun95** [comment]
I get the same error as yours, do you figure it out?

**Comment by JulioEndara** [comment]
In case it helps: I was having the same issue. In my case I had forgotten to create the train and test list.

**Comment by geroge-gao** [comment]
@joul55320 I have the train.list , but I still got the issue.
