### ISSUE TITLE
EOFerror when python Random_clip_valid.py

### ISSUE THREAD

**Issue by cckenny** [hx173149/C3D-tensorflow#53]
2%|▏         | 29/1261 [00:08<06:00,  3.41it/s]test acc: 0.8620689655172413 test_correct_num: 75 total_v: 87.0
Loading a video clip from F:/UCF-101//Archery/v_Archery_g06_c06...
Loading a video clip from F:/UCF-101//Archery/v_Archery_g07_c04...

Traceback (most recent call last):
  File "E:/graduate/action-recognition/code/Random_clip_valid.py", line 197, in <module>
    modelpath="./")
  File "E:/graduate/action-recognition/code/Random_clip_valid.py", line 184, in test
    shuffle=False
  File "E:\graduate\action-recognition\code\input_data_v1.py", line 97, in read_clip_and_label
    raise EOFError
EOFError

Process finished with exit code 1

Thanks

**Comment by cckenny** [comment]
I passed it but am I right？

**Comment by cckenny** [comment]
what's more i wonder why my accuracy is always 1.0 during the whole training?
the predict result is right i guess At least they are  between 0 and 1.0

**Comment by binhhoangtieu** [comment]
This error may be caused by the number of extracted file is less than 16 (look into this folder F:/UCF-101//Archery/v_Archery_g07_c04)

**Comment by cckenny** [comment]
thanks，u r right.but why? i used the shell code in ubuntu to extract those frames.
do you know why  my accuracy is always 1.0 during the whole training?

**Comment by cckenny** [comment]
I saw your comment I think our accuracy may have the same bug.

**Comment by binhhoangtieu** [comment]
> thanks，u r right.but why? i used the shell code in ubuntu to extract those frames.
<

Because your video is not long enough, you can change the file "convert_video_to_images.sh" for extracting more frames

>do you know why my accuracy is always 1.0 during the whole training?<

I'm not sure but you should check your downloaded files (models), train.list and test.list (you should modify this path before training (do not use original train.list and test.list)

Hope this helps

**Comment by ZhiQue930716** [comment]
@cckenny i met the same error,how did you fixed this ?

**Comment by PBRAOS** [comment]
there is a simple fix. just comment the Error exceptions.

**Comment by Luhn-Saul** [comment]
> > thanks，u r right.but why? i used the shell code in ubuntu to extract those frames.
> 
> Because your video is not long enough, you can change the file "convert_video_to_images.sh" for extracting more frames
> 
> > do you know why my accuracy is always 1.0 during the whole training?
> 
> I'm not sure but you should check your downloaded files (models, train.list and test.list), you should modify this path before training (do not use original train.list and test.list)
> 
> Hope this helps

Many of the extracted documents are less than 16(eg.:Archery/v_Archery_g05_c04,Archery/v_Archery_g07_c02&c03&c04&c05&c06,and Archery/v_Archery_g17_c04,and BalanceBeam/v_BalanceBeam_g02_c03,and BalanceBeam/v_BalanceBeam_g03_c04,and BalanceBeam/v_BalanceBeam_g10_c02,and BalanceBeam/v_BalanceBeam_g11_c02,and BalanceBeam/v_BalanceBeam_g12_c01&02,and BalanceBeam/v_BalanceBeam_g13_c04,ect.) Can changing the file "convert_video_to_images.sh" really solve the problem?

**Comment by Luhn-Saul** [comment]
> > thanks，u r right.but why? i used the shell code in ubuntu to extract those frames.
> 
> Because your video is not long enough, you can change the file "convert_video_to_images.sh" for extracting more frames
> 
> > do you know why my accuracy is always 1.0 during the whole training?
> 
> I'm not sure but you should check your downloaded files (models, train.list and test.list), you should modify this path before training (do not use original train.list and test.list)
> 
> Hope this helps

Many of the extracted documents are less than 16(eg.:Archery/v_Archery_g05_c04,Archery/v_Archery_g07_c02&c03&c04&c05&c06,and Archery/v_Archery_g17_c04,and BalanceBeam/v_BalanceBeam_g02_c03,and BalanceBeam/v_BalanceBeam_g03_c04,and BalanceBeam/v_BalanceBeam_g10_c02,and BalanceBeam/v_BalanceBeam_g11_c02,and BalanceBeam/v_BalanceBeam_g12_c01&02,and BalanceBeam/v_BalanceBeam_g13_c04,ect.) Can changing the file "convert_video_to_images.sh" really solve the problem?
Thank you  and I will be looking forward to your reply.

**Comment by cckenny** [comment]
yeap

Luhn-Saul <notifications@github.com> 于2019年2月17日周日 下午1:53写道：

**Comment by Luhn-Saul** [comment]
All right. Could you tell me detailedly how you changing it?
I hope to get your help! Thanks.
