### ISSUE TITLE
weight.values,bias.values error

### ISSUE THREAD

**Issue by abhisheksurya578** [hx173149/C3D-tensorflow#98]
Hi @hx173149 @gudongfeng @chuckcho @cc786537662  

 File "/home/ltroot/data1/C3D-tensorflow-master/train_c3d_ucf101.py", line 171, in run_training
    varlist1 = list(set(weights.values() + biases.values()) - set(varlist2))
TypeError: unsupported operand type(s) for +: 'dict_values' and 'dict_values'

**Comment by highway007** [comment]
Hi ,change to:
**varlist1 = list( set(list(weights.values()) + list(biases.values())) - set(varlist2) )**
and see if it work

**Comment by abhisheksurya578** [comment]
Hello

Thanks the issue is resolved now.But 
ValueError: Cannot feed value of shape (10, 0) for Tensor u'Placeholder:0', which has shape '(?, 16, 128, 128, 3)'

Can you please suggest what could be the problem?

**Comment by highway007** [comment]
@abhisheksurya578 Can you post the whole terminal output?
And I think this issue is something about py3 and py2 .Authers's code was base on py2 , however you did this on py3 . (Right? You can run it on py3 after changed some code also)

**Comment by abhisheksurya578** [comment]
thanks for responding @highway007 , @hx173149 
/home/ltroot/PycharmProjects/C3D/venv/bin/python /home/ltroot/data1/C3D-tensorflow-master/train_c3d_ucf101.py
2019-03-18 05:26:10.050805: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2019-03-18 05:26:10.050833: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2019-03-18 05:26:10.050838: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2019-03-18 05:26:10.050843: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2019-03-18 05:26:10.050848: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "/home/ltroot/data1/C3D-tensorflow-master/train_c3d_ucf101.py", line 262, in <module>
    tf.app.run()
  File "/home/ltroot/PycharmProjects/C3D/venv/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/ltroot/data1/C3D-tensorflow-master/train_c3d_ucf101.py", line 259, in main
    run_training()
  File "/home/ltroot/data1/C3D-tensorflow-master/train_c3d_ucf101.py", line 224, in run_training
    labels_placeholder: train_labels
  File "/home/ltroot/PycharmProjects/C3D/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/ltroot/PycharmProjects/C3D/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 975, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (20, 0) for Tensor 'Placeholder:0', which has shape '(20, 16, 112, 112, 3)'
help me to resolve this

**Comment by abhisheksurya578** [comment]
Traceback (most recent call last):
File "/home/ltroot/data1/C3D-tensorflow-master/train_c3d_ucf101.py", line 262, in 
tf.app.run()
File "/home/ltroot/PycharmProjects/C3D/venv/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
_sys.exit(main(_sys.argv[:1] + flags_passthrough))
File "/home/ltroot/data1/C3D-tensorflow-master/train_c3d_ucf101.py", line 259, in main
run_training()
File "/home/ltroot/data1/C3D-tensorflow-master/train_c3d_ucf101.py", line 224, in run_training
labels_placeholder: train_labels
File "/home/ltroot/PycharmProjects/C3D/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 789, in run
run_metadata_ptr)
File "/home/ltroot/PycharmProjects/C3D/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 975, in _run
% (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (20, 0) for Tensor 'Placeholder:0', which has shape '(20, 16, 112, 112, 3)'
help me to resolve this

**Comment by highway007** [comment]
@abhisheksurya578 So did you run the demo with your own dataset? Can you show me lines of your train.list?

**Comment by abhisheksurya578** [comment]
No I haven't tried on my own dataset.I have used ucf-101 and your
train.list and test.list from git repository.

**Comment by highway007** [comment]
@abhisheksurya578 My list isn't for ucf101,you should run ./list/**** like the readme to get it.(you should download the ucf101 dataset also.

**Comment by abhisheksurya578** [comment]
Our Train.list

/ds_data/ucfimgs/ApplyEyeMakeup/v_ApplyEyeMakeup_g08_c01 0
/ds_data/ucfimgs/ApplyEyeMakeup/v_ApplyEyeMakeup_g08_c02 0
/ds_data/ucfimgs/ApplyEyeMakeup/v_ApplyEyeMakeup_g08_c03 0
/ds_data/ucfimgs/ApplyEyeMakeup/v_ApplyEyeMakeup_g08_c04 0
/ds_data/ucfimgs/ApplyEyeMakeup/v_ApplyEyeMakeup_g08_c05 0
/ds_data/ucfimgs/ApplyEyeMakeup/v_ApplyEyeMakeup_g09_c01 0
/ds_data/ucfimgs/ApplyEyeMakeup/v_ApplyEyeMakeup_g09_c02 0
/ds_data/ucfimgs/ApplyEyeMakeup/v_ApplyEyeMakeup_g09_c03 0


our Test.list

/ds_data/ucfimgs/ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c01 0
/ds_data/ucfimgs/ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c02 0
/ds_data/ucfimgs/ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c03 0
/ds_data/ucfimgs/ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c04 0
/ds_data/ucfimgs/ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c05 0
/ds_data/ucfimgs/ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c06 0
/ds_data/ucfimgs/ApplyEyeMakeup/v_ApplyEyeMakeup_g02_c01 0
/ds_data/ucfimgs/ApplyEyeMakeup/v_ApplyEyeMakeup_g02_c02 0
/ds_data/ucfimgs/ApplyEyeMakeup/v_ApplyEyeMakeup_g02_c03 0
/ds_data/ucfimgs/ApplyEyeMakeup/v_ApplyEyeMakeup_g02_c04 0
/ds_data/ucfimgs/ApplyEyeMakeup/v_ApplyEyeMakeup_g03_c01 0
/ds_data/ucfimgs/ApplyEyeMakeup/v_ApplyEyeMakeup_g03_c02 0
/ds_data/ucfimgs/ApplyEyeMakeup/v_ApplyEyeMakeup_g03_c03 0
/ds_data/ucfimgs/ApplyEyeMakeup/v_ApplyEyeMakeup_g03_c04 0
/ds_data/ucfimgs/ApplyEyeMakeup/v_ApplyEyeMakeup_g03_c05 0
/ds_data/ucfimgs/ApplyEyeMakeup/v_ApplyEyeMakeup_g03_c06 0






*We tried running convert_videos to imgs.sh but we  end up with
following error./list/convert_video_to_images.sh: line 25: ffmpeg:
command not foundrm: cannot remove 'ds_data/UCF-101/*/*.avi': No such
file or directory*

*Inside the UCF-101 dataset every video file got erased and only
folder structure exists.*


*If we tried with existing train.list and test.list by modifying path
inside train.list and test.list paths.*

2019-03-21 13:37:33.719790: I
tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device
(0): <undefined>, <undefined>
WARNING:tensorflow:From
/root/PycharmProjects/c3d/venv/lib/python3.5/site-packages/tensorflow/python/training/saver.py:1266:
checkpoint_exists (from tensorflow.python.training.checkpoint_management)
is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Traceback (most recent call last):
  File "/home/ltroot/Downloads/C3D-tensorflow-master/train_c3d_ucf101.py",
line 261, in <module>
    tf.app.run()
  File
"/root/PycharmProjects/c3d/venv/lib/python3.5/site-packages/tensorflow/python/platform/app.py",
line 125, in run
    _sys.exit(main(argv))
  File "/home/ltroot/Downloads/C3D-tensorflow-master/train_c3d_ucf101.py",
line 258, in main
    run_training()
  File "/home/ltroot/Downloads/C3D-tensorflow-master/train_c3d_ucf101.py",
line 223, in run_training
    labels_placeholder: train_labels
  File
"/root/PycharmProjects/c3d/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py",
line 929, in run
    run_metadata_ptr)
  File
"/root/PycharmProjects/c3d/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py",
line 1128, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (20, 0) for Tensor 'Placeholder:0',
which has shape '(20, 16, 112, 112, 3)'

**Comment by highway007** [comment]
@abhisheksurya578 hi, you should make sure that `./list/convert_video_to_images.sh *** 5` is the same name with your ucf101 file.It is a issue that path in your list is different from path in error.suggest you check file name carefully.

**Comment by abhisheksurya578** [comment]
Hello I’m done with running video to img and img to list.sh files.But while
running train.py I’m facing this issue

tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device
(0): <undefined>, <undefined>
WARNING:tensorflow:From /root/PycharmProjects/c3d/venv/lib/python3.5/site-
packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from
tensorflow.python.training.checkpoint_management) is deprecated and will be
removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Traceback (most recent call last):
  File "/home/ltroot/Downloads/C3D-tensorflow-master/train_c3d_ucf101.py",
line 261, in <module>
    tf.app.run()
  File "/root/PycharmProjects/c3d/venv/lib/python3.5/site-
packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/ltroot/Downloads/C3D-tensorflow-master/train_c3d_ucf101.py",
line 258, in main
    run_training()
  File "/home/ltroot/Downloads/C3D-tensorflow-master/train_c3d_ucf101.py",
line 223, in run_training
    labels_placeholder: train_labels
  File "/root/PycharmProjects/c3d/venv/lib/python3.5/site-
packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File
"/root/PycharmProjects/c3d/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py",
line 1128, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (20, 0) for Tensor 'Placeholder:0',
which has shape '(20, 16, 112, 112, 3)

**Comment by highway007** [comment]
@abhisheksurya578 Can you see the images from the path in your train.list?

**Comment by abhisheksurya578** [comment]
No I can just see the image paths not images

**Comment by highway007** [comment]
@abhisheksurya578 if you run video to img and img to list.sh successfully,you can see images with the path in train.list.

**Comment by abhisheksurya578** [comment]
Yeah I successfully ran video to img and img to list.sh but I’m facing the
issue

**Comment by highway007** [comment]
@abhisheksurya578 There must be some error when you run .sh :(

**Comment by abhisheksurya578** [comment]
Hello ,

i have successfully trained UCF for 101 classes.But I just wanna train for
16 classes.I have changed the parameter no of classes to 16.It worked when
i make use_pretrain=FALSE.
If i use sports_1m  fine tune model weights I got the following error.
How to use sports1m for 16 classes and Is there any parameter we need to
change for 16 classes.

Use standard file APIs to check for files with this prefix.
Traceback (most recent call last):
  File
"/root/PycharmProjects/c3d/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py",
line 1334, in _do_call
    return fn(*args)
  File
"/root/PycharmProjects/c3d/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py",
line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File
"/root/PycharmProjects/c3d/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py",
line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign
requires shapes of both tensors to match. lhs shape= [4096,16] rhs shape=
[4096,101]
     [[{{node save/Assign_21}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File
"/root/PycharmProjects/c3d/venv/lib/python3.5/site-packages/tensorflow/python/training/saver.py",
line 1276, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File
"/root/PycharmProjects/c3d/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py",
line 929, in run
    run_metadata_ptr)
  File
"/root/PycharmProjects/c3d/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py",
line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File
"/root/PycharmProjects/c3d/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py",
line 1328, in _do_run
    run_metadata)
  File
"/root/PycharmProjects/c3d/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py",
line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign
requires shapes of both tensors to match. lhs shape= [4096,16] rhs shape=
[4096,101]
     [[node save/Assign_21 (defined at
/home/ltroot/Downloads/C3D-tensorflow-master/train_c3d_ucf101.py:197) ]]

Caused by op 'save/Assign_21', defined at:
  File "/home/ltroot/Downloads/C3D-tensorflow-master/train_c3d_ucf101.py",
line 261, in <module>
    tf.app.run()
  File
"/root/PycharmProjects/c3d/venv/lib/python3.5/site-packages/tensorflow/python/platform/app.py",
line 125, in run
    _sys.exit(main(argv))
  File "/home/ltroot/Downloads/C3D-tensorflow-master/train_c3d_ucf101.py",
line 258, in main
    run_training()
  File "/home/ltroot/Downloads/C3D-tensorflow-master/train_c3d_ucf101.py",
line 197, in run_training
    saver = tf.train.Saver(list(weights.values()) + list(biases.values()))
  File
"/root/PycharmProjects/c3d/venv/lib/python3.5/site-packages/tensorflow/python/training/saver.py",
line 832, in __init__
    self.build()
  File
"/root/PycharmProjects/c3d/venv/lib/python3.5/site-packages/tensorflow/python/training/saver.py",
line 844, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File
"/root/PycharmProjects/c3d/venv/lib/python3.5/site-packages/tensorflow/python/training/saver.py",
line 881, in _build
    build_save=build_save, build_restore=build_restore)
  File
"/root/PycharmProjects/c3d/venv/lib/python3.5/site-packages/tensorflow/python/training/saver.py",
line 513, in _build_internal
    restore_sequentially, reshape)
  File
"/root/PycharmProjects/c3d/venv/lib/python3.5/site-packages/tensorflow/python/training/saver.py",
line 354, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File
"/root/PycharmProjects/c3d/venv/lib/python3.5/site-packages/tensorflow/python/training/saving/saveable_object_util.py",
line 73, in restore
    self.op.get_shape().is_fully_defined())
  File
"/root/PycharmProjects/c3d/venv/lib/python3.5/site-packages/tensorflow/python/ops/state_ops.py",
line 223, in assign
    validate_shape=validate_shape)
  File
"/root/PycharmProjects/c3d/venv/lib/python3.5/site-packages/tensorflow/python/ops/gen_state_ops.py",
line 64, in assign
    use_locking=use_locking, name=name)
  File
"/root/PycharmProjects/c3d/venv/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py",
line 788, in _apply_op_helper
    op_def=op_def)
  File
"/root/PycharmProjects/c3d/venv/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py",
line 507, in new_func
    return func(*args, **kwargs)
  File
"/root/PycharmProjects/c3d/venv/lib/python3.5/site-packages/tensorflow/python/framework/ops.py",
line 3300, in create_op
    op_def=op_def)
  File
"/root/PycharmProjects/c3d/venv/lib/python3.5/site-packages/tensorflow/python/framework/ops.py",
line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Assign requires shapes of
both tensors to match. lhs shape= [4096,16] rhs shape= [4096,101]
     [[node save/Assign_21 (defined at
/home/ltroot/Downloads/C3D-tensorflow-master/train_c3d_ucf101.py:197) ]]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ltroot/Downloads/C3D-tensorflow-master/train_c3d_ucf101.py",
line 261, in <module>
    tf.app.run()
  File
"/root/PycharmProjects/c3d/venv/lib/python3.5/site-packages/tensorflow/python/platform/app.py",
line 125, in run
    _sys.exit(main(argv))
  File "/home/ltroot/Downloads/C3D-tensorflow-master/train_c3d_ucf101.py",
line 258, in main
    run_training()
  File "/home/ltroot/Downloads/C3D-tensorflow-master/train_c3d_ucf101.py",
line 206, in run_training
    saver.restore(sess, model_filename)
  File
"/root/PycharmProjects/c3d/venv/lib/python3.5/site-packages/tensorflow/python/training/saver.py",
line 1312, in restore
    err, "a mismatch between the current graph and the graph")
tensorflow.python.framework.errors_impl.InvalidArgumentError: Restoring
from checkpoint failed. This is most likely due to a mismatch between the
current graph and the graph from the checkpoint. Please ensure that you
have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [4096,16] rhs
shape= [4096,101]
     [[node save/Assign_21 (defined at
/home/ltroot/Downloads/C3D-tensorflow-master/train_c3d_ucf101.py:197) ]]

Caused by op 'save/Assign_21', defined at:
  File "/home/ltroot/Downloads/C3D-tensorflow-master/train_c3d_ucf101.py",
line 261, in <module>
    tf.app.run()
  File
"/root/PycharmProjects/c3d/venv/lib/python3.5/site-packages/tensorflow/python/platform/app.py",
line 125, in run
    _sys.exit(main(argv))
  File "/home/ltroot/Downloads/C3D-tensorflow-master/train_c3d_ucf101.py",
line 258, in main
    run_training()
  File "/home/ltroot/Downloads/C3D-tensorflow-master/train_c3d_ucf101.py",
line 197, in run_training
    saver = tf.train.Saver(list(weights.values()) + list(biases.values()))
  File
"/root/PycharmProjects/c3d/venv/lib/python3.5/site-packages/tensorflow/python/training/saver.py",
line 832, in __init__
    self.build()
  File
"/root/PycharmProjects/c3d/venv/lib/python3.5/site-packages/tensorflow/python/training/saver.py",
line 844, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File
"/root/PycharmProjects/c3d/venv/lib/python3.5/site-packages/tensorflow/python/training/saver.py",
line 881, in _build
    build_save=build_save, build_restore=build_restore)
  File
"/root/PycharmProjects/c3d/venv/lib/python3.5/site-packages/tensorflow/python/training/saver.py",
line 513, in _build_internal
    restore_sequentially, reshape)
  File
"/root/PycharmProjects/c3d/venv/lib/python3.5/site-packages/tensorflow/python/training/saver.py",
line 354, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File
"/root/PycharmProjects/c3d/venv/lib/python3.5/site-packages/tensorflow/python/training/saving/saveable_object_util.py",
line 73, in restore
    self.op.get_shape().is_fully_defined())
  File
"/root/PycharmProjects/c3d/venv/lib/python3.5/site-packages/tensorflow/python/ops/state_ops.py",
line 223, in assign
    validate_shape=validate_shape)
  File
"/root/PycharmProjects/c3d/venv/lib/python3.5/site-packages/tensorflow/python/ops/gen_state_ops.py",
line 64, in assign
    use_locking=use_locking, name=name)
  File
"/root/PycharmProjects/c3d/venv/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py",
line 788, in _apply_op_helper
    op_def=op_def)
  File
"/root/PycharmProjects/c3d/venv/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py",
line 507, in new_func
    return func(*args, **kwargs)
  File
"/root/PycharmProjects/c3d/venv/lib/python3.5/site-packages/tensorflow/python/framework/ops.py",
line 3300, in create_op
    op_def=op_def)
  File
"/root/PycharmProjects/c3d/venv/lib/python3.5/site-packages/tensorflow/python/framework/ops.py",
line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Restoring from checkpoint
failed. This is most likely due to a mismatch between the current graph and
the graph from the checkpoint. Please ensure that you have not altered the
graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [4096,16] rhs
shape= [4096,101]
     [[node save/Assign_21 (defined at
/home/ltroot/Downloads/C3D-tensorflow-master/train_c3d_ucf101.py:197) ]]
Please help

**Comment by AndyHon** [comment]
Cannot feed value of shape (11, 16, 160, 160, 3) for Tensor 'Placeholder:0', which has shape '(12, 16, 160, 160, 3)'
What should I do about it?help me,thanks
