### ISSUE TITLE
Issue in Training!!!!

### ISSUE THREAD

**Issue by abhisheksurya578** [hx173149/C3D-tensorflow#99]
Hi @gudongfeng @hx173149 @chuckcho @cc786537662 

ValueError: Cannot feed value of shape (40, 0) for Tensor u'Placeholder:0', which has shape '(?, 16, 128, 128, 3)'

Can you please suggest what could be the problem?

**Comment by abhisheksurya578** [comment]
Traceback (most recent call last):
File "/home/ltroot/data1/C3D-tensorflow-master/train_c3d_ucf101.py", line 262, in 
tf.app.run()
File "/home/ltroot/PycharmProjects/C3D/venv/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
_sys.exit(main(_sys.argv[:1] + flags_passthrough))
File "/home/ltroot/data1/C3D-tensorflow-master/train_c3d_ucf101.py", line 259, in main
run_training()
File "/home/ltroot/data1/C3D-tensorflow-master/train_c3d_ucf101.py", line 224, in run_training
labels_placeholder: train_labels
File "/home/ltroot/PycharmProjects/C3D/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 789, in run
run_metadata_ptr)
File "/home/ltroot/PycharmProjects/C3D/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 975, in _run
% (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (20, 0) for Tensor 'Placeholder:0', which has shape '(20, 16, 112, 112, 3)'
help me to resolve this

**Comment by Shiny128** [comment]
Hello,
 Please Check the following issue , helped me solve a similar error
Duplicate of #47

**Comment by abhisheksurya578** [comment]
Hello @Shiny128 @gudongfeng @hx173149 @chuckcho @highway007

I want to train the model with new Dataset .

How to create crop_mean.npy file for new dataset?

What are the changes to be made to C3D model?(Removing the final layers)

I wanna detect the object in the video as well how to do this?

Can anyone please guide me...

**Comment by qizhiliu0639** [comment]
> Traceback (most recent call last):
> File "/home/ltroot/data1/C3D-tensorflow-master/train_c3d_ucf101.py", line 262, in
> tf.app.run()
> File "/home/ltroot/PycharmProjects/C3D/venv/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
> _sys.exit(main(_sys.argv[:1] + flags_passthrough))
> File "/home/ltroot/data1/C3D-tensorflow-master/train_c3d_ucf101.py", line 259, in main
> run_training()
> File "/home/ltroot/data1/C3D-tensorflow-master/train_c3d_ucf101.py", line 224, in run_training
> labels_placeholder: train_labels
> File "/home/ltroot/PycharmProjects/C3D/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 789, in run
> run_metadata_ptr)
> File "/home/ltroot/PycharmProjects/C3D/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 975, in _run
> % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
> ValueError: Cannot feed value of shape (20, 0) for Tensor 'Placeholder:0', which has shape '(20, 16, 112, 112, 3)'
> help me to resolve this

I have met this problem before, it might be the input_data.py's problem, it didn't read your file.  You maybe need to do a little change to the os.walk()
